name: Security Testing


on:
  push:
    branches:
      - rishika-final-capstone
  pull_request:


  workflow_dispatch:

jobs:
  security:
    name: API Security Tests
    runs-on: ubuntu-latest
    defaults:

      run:

        working-directory: api-Automation



    steps:



      - name: Checkout Code

        uses: actions/checkout@v4




      - name: Setup Java 22

        uses: actions/setup-java@v4

        with:

          java-version: '22'

          distribution: temurin

          cache: maven




      - name: Run Security Tests

        run:

          mvn clean test -Dtest="*SecurityTest"




      - name: Upload Security Reports

        if: always()

        uses: actions/upload-artifact@v4

        with:

          name: security-test-report

          path: api-Automation/target/surefire-reports