name: Security Testing

on:
  push:
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api-Automation
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version:22          
          distribution:temurin
      - name: Run Security Tests
        run:
          mvn test -Dtest="*SecurityTest"