// import { test, expect } from '@playwright/test';

// //this file is without using any frameworks
// // i created a second test file which cointains test with all logs and structured frameworks for reusebality
// test('oneway trip', async ({ page }) => {
//   await page.goto('/');
//   await page.getByRole('link', { name: 'Log in' }).click();
//   await page.getByRole('textbox', { name: 'Email' }).fill('karl@tripstack.test');
//   await page.getByRole('textbox', { name: 'Password' }).fill('Password@123');
//   await page.getByRole('button', { name: 'Sign in' }).click();
//   await expect(page.getByRole('heading', { name: 'Book flights & buses across' })).toBeVisible();
//   await page.getByRole('combobox', { name: 'From' }).fill('jai');
//   await page.getByRole('option', { name: 'Jaipur JAI' }).click();
//   await page.getByRole('combobox', { name: 'To' }).fill('bom');
//   await page.getByRole('option', { name: 'Mumbai BOM' }).click();
//   await page.getByRole('textbox', { name: 'Date' }).fill('2026-07-17');
//   await page.getByRole('button', { name: 'Search' }).click();
//   await expect(page.getByRole('heading', { name: 'Flights: JAI → BOM' })).toBeVisible();
//   await expect(page.getByRole('article', { name: 'IndiGo 6E-483' })).toBeVisible();
//   await page.getByLabel('IndiGo 6E-483').getByRole('button', { name: 'Book' }).click();
//   await expect(page.getByRole('heading', { name: 'Choose your seats' })).toBeVisible();
//   await page.getByLabel('Seat 1A, window, available').click();
//   await page.getByRole('button', {name: 'Continue to passenger details'}).click();
//   await expect(page.getByRole('heading', {name: "Who's travelling?"})).toBeVisible();
//   await page.locator("#name-1A").fill("Hemanth");
//   await page.locator("#lastname-1A").fill("Reddy");
//   await page.locator("#age-1A").fill("25");
//   await page.locator("#gender-1A").selectOption("male");
//   await page.getByRole('textbox', { name: 'Email' }).click();
//   await page.getByRole('textbox', { name: 'Email' }).fill('karl@tripstack.test');
//   await page.getByRole('textbox', { name: 'Phone number' }).click();
//   await page.getByRole('textbox', { name: 'Phone number' }).fill('7301123456');
//   await page.getByRole('button', { name: 'Continue to payment' }).click();
//   await page.getByRole('textbox', { name: 'Name on card' }).fill('karl');
//   await page.getByRole('textbox', { name: 'Card number' }).fill('1234567812345678');
//   await page.getByRole('textbox', { name: 'Expiry' }).fill('0130');
//   await page.getByRole('textbox', { name: 'CVV' }).fill('897');
//   await page.getByRole('button', { name: 'Pay ₹' }).click();
//   await expect(page.getByRole('heading', { name: 'You\'re all set! 🎉' })).toBeVisible();
//   await expect(page.getByText('Booking reference (PNR)')).toBeVisible();
//   await expect(page.getByText('Amount paid')).toBeVisible();
// });

// test('return trip - no Flights found on the return trip', async ({ page }) => {
//   await page.goto('/');
//   await page.getByRole('link', { name: 'Log in' }).click();
//   await page.getByRole('textbox', { name: 'Email' }).fill('karl@tripstack.test');
//   await page.getByRole('textbox', { name: 'Password' }).fill('Password@123');
//   await page.getByRole('button', { name: 'Sign in' }).click();
//   await expect(page.getByRole('heading', { name: 'Book flights & buses across' })).toBeVisible();
//   await page.getByRole('combobox', { name: 'From' }).fill('bom');
//   await page.getByRole('option', { name: 'Mumbai BOM' }).click();
//   await page.getByRole('combobox', { name: 'To' }).fill('jai');
//   await page.getByRole('option', { name: 'Jaipur JAI' }).click();
//   await page.getByRole('textbox', { name: 'Date' }).fill('2026-08-15');
//   await page.getByRole('button', { name: 'Search' }).click();
//   await expect(page.getByRole('heading', { name: 'Flights: BOM → JAI' })).toBeVisible();
//   await expect(page.getByRole('article', { name: 'IndiGo 6E-483-R' })).toBeVisible();
//   await page.getByLabel('IndiGo 6E-483-R').getByRole('button', { name: 'Book' }).click();
//   await expect(page.getByRole('heading', { name: 'Choose your seats' })).toBeVisible();
//   await page.getByLabel('Seat 1A, window, available').click();
//   await page.getByRole('button', {name: 'Continue to passenger details'}).click();
//   await expect(page.getByRole('heading', {name: "Who's travelling?"})).toBeVisible();
//   await page.locator("#name-1A").fill("Hemanth");
//   await page.locator("#lastname-1A").fill("Reddy");
//   await page.locator("#age-1A").fill("25");
//   await page.locator("#gender-1A").selectOption("male");
//   await page.getByRole('textbox', { name: 'Email' }).click();
//   await page.getByRole('textbox', { name: 'Email' }).fill('karl@tripstack.test');
//   await page.getByRole('textbox', { name: 'Phone number' }).click();
//   await page.getByRole('textbox', { name: 'Phone number' }).fill('7301123456');
//   await page.getByRole('button', { name: 'Continue to payment' }).click();
//   await page.getByRole('textbox', { name: 'Name on card' }).fill('karl');
//   await page.getByRole('textbox', { name: 'Card number' }).fill('1234567812345678');
//   await page.getByRole('textbox', { name: 'Expiry' }).fill('0130');
//   await page.getByRole('textbox', { name: 'CVV' }).fill('897');
//   await page.getByRole('button', { name: 'Pay ₹' }).click();
//   await expect(page.getByRole('heading', { name: 'You\'re all set! 🎉' })).toBeVisible();
//   await expect(page.getByText('Booking reference (PNR)')).toBeVisible();
//   await expect(page.getByText('Amount paid')).toBeVisible();
// });