import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://tripstack.doomple.com/');
  await expect(page.getByRole('tab', { name: 'Flights' })).toBeVisible();
  await page.getByRole('combobox', { name: 'From' }).click();
  await page.getByRole('combobox', { name: 'From' }).fill('Mumbai');
  await page.getByRole('option', { name: 'Mumbai BOM' }).click();
  await page.getByRole('combobox', { name: 'To' }).click();
  await page.getByRole('combobox', { name: 'To' }).fill('Chennai');
  await page.getByRole('option', { name: 'Chennai MAA' }).click();
  await page.getByRole('textbox', { name: 'Date' }).fill('2026-07-24');
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByRole('checkbox', { name: 'IndiGo' }).check();
  await page.getByRole('checkbox', { name: 'Vistara' }).check();
  await page.getByRole('checkbox', { name: 'SpiceJet' }).check();
  await page.getByRole('checkbox', { name: 'Air India' }).check();
  await page.getByRole('checkbox', { name: 'Before 6 AM' }).check();
  await page.getByRole('checkbox', { name: 'AM – 12 PM' }).check();
  await page.getByRole('checkbox', { name: 'PM – 6 PM' }).check();
  await page.getByRole('checkbox', { name: 'After 6 PM' }).check();
  await page.getByRole('slider', { name: 'Maximum price' }).fill('641306');
  await expect(page.getByRole('button', { name: 'Departure' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Flights: BOM → MAA' })).toBeVisible();
  await expect(page.getByLabel('IndiGo 6E-494').getByRole('button', { name: 'Book' })).toBeVisible();
  await page.getByText('IndiGo 6E-494').click();
  await page.getByLabel('IndiGo 6E-494').getByRole('button', { name: 'Book' }).click();
  await expect(page.getByText('Available')).toBeVisible();
  await page.getByLabel('Seat 3A, window, available').click();
  await page.getByLabel('Seat 3A, window, available').click();
  await page.getByText('3Passenger').click();
  await page.getByText('IndiGo').click();
  await page.getByText('BOM 05:57 → MAA 08:').click();
  await page.getByLabel('Seat 2D, aisle, available').click();
  await page.getByText('3Passenger').click();
  await page.getByRole('link', { name: 'Log in' }).click();
  await page.getByText('dave@tripstack.test').click();
  await page.getByText('dave@tripstack.test').click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('dave@tripstack.test');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Password@123');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('combobox', { name: 'From' }).click();
  await page.getByRole('option', { name: 'Ahmedabad AMD' }).click();
  await page.getByRole('combobox', { name: 'To' }).click();
  await page.getByRole('option', { name: 'Ahmedabad AMD' }).click();
  await page.getByRole('combobox', { name: 'To' }).click();
  await page.getByRole('combobox', { name: 'To' }).click();
  await page.getByRole('combobox', { name: 'To' }).fill('');
  await page.getByRole('option', { name: 'Chennai MAA' }).click();
  await page.getByRole('textbox', { name: 'Date' }).fill('2026-07-18');
  await expect(page.getByRole('link', { name: 'Delhi → Mumbai' })).toBeVisible();
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByRole('combobox', { name: 'From' }).click();
  await page.getByRole('link', { name: 'Kolkata → Delhi' }).click();
  await page.getByRole('checkbox', { name: 'SpiceJet' }).check();
  await page.getByRole('checkbox', { name: 'Air India' }).check();
  await page.getByRole('checkbox', { name: 'IndiGo' }).check();
  await page.getByText('Vistara', { exact: true }).click();
  await page.getByRole('checkbox', { name: 'Before 6 AM' }).check();
  await page.getByText('AM – 12 PM').click();
  await page.getByRole('checkbox', { name: 'PM – 6 PM' }).check();
  await page.getByRole('checkbox', { name: 'After 6 PM' }).check();
  await page.getByRole('slider', { name: 'Maximum price' }).fill('724859');
  await page.getByLabel('IndiGo 6E-170').getByRole('button', { name: 'Book' }).click();
  await page.getByLabel('Seat 3A, window, available').click();
  await page.getByText('3Passenger').click();
  await page.getByText('4Payment').click();
  await page.getByText('3Passenger').dblclick();
});