name: Provider Verification

on:
  workflow_run:
    workflows: ["Consumer Contract"]
    types:
      - completed

  workflow_dispatch:

jobs:

  provider:

    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 22
          cache: maven

      - name: Install Pact CLI
        run: |
          curl -fsSL https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v2.4.5/pact-2.4.5-linux-x86_64.tar.gz | tar xz -C $HOME
          echo "$HOME/pact/bin" >> $GITHUB_PATH

      - name: Start Pact Broker
        run: |
          docker compose -f src/test/resources/docker-compose.pact-broker.yml up -d --wait

      - name: Verify Provider
        run: |
          mvn clean test \
            -Dtest=OmsProviderPactTest \
            -Dgit.sha=${{ github.sha }} \
            -Dpactbroker.host=127.0.0.1 \
            -Dpactbroker.port=9292

      - name: Record Deployment
        run: |
          pact-broker record-deployment \
            --pacticipant oms-provider \
            --version ${{ github.sha }} \
            --environment production \
            --broker-base-url=http://127.0.0.1:9292

      - name: Can I Deploy
        run: |
          pact-broker can-i-deploy \
            --pacticipant pos-consumer \
            --version ${{ github.sha }} \
            --to-environment production \
            --broker-base-url=http://127.0.0.1:9292