name: Provider Verification

on:
  workflow_dispatch:

jobs:
  provider:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '22'

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}

      - name: Start Pact Broker
        working-directory: Selenide_and_Wiremock
        run: |
          docker compose -f src/test/resources/docker-compose.pact-broker.yml up -d

      - name: Wait for Broker
        working-directory: Selenide_and_Wiremock
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:9292/diagnostic/status/heartbeat; then
              exit 0
            fi
            sleep 5
          done
          exit 1

      - name: Run Provider Verification
        working-directory: Selenide_and_Wiremock
        run: |
          mvn \
            -Dtest=OmsProviderVerification \
            -Dgit.sha=${GITHUB_SHA::7} \
            -Dgit.branch=${GITHUB_REF_NAME} \
            test