import {test, expect} from '@playwright/test';
import {testUsers} from '../fixtures/test-users';
test.describe("Week1 capstone ",()=>{
    test('Entire WorkFlow',async({page})=>{
        await page.goto('/home');
        await expect(page.getByRole('heading',{name:"SDET Retail Automation Lab"})).toBeVisible();
        await page.getByRole('link',{name:'Sign in'}).click();
        await expect(page).toHaveURL(/\/login$/);
        await expect(page.getByRole('heading',{name:'Sign in to Retail Lab'})).toBeVisible();
        const LoginForm = page.getByRole("form", {name: "Login"});
                await LoginForm.getByLabel("Email").fill(testUsers.customer.email);
                await LoginForm.getByLabel("Password").fill(testUsers.customer.password);
                await LoginForm.getByLabel("Country").selectOption({label:"India"});
                await LoginForm.getByLabel("Remember me").click();
                await LoginForm.getByRole("button", { name: "Sign in" }).click();
         await expect(page).toHaveURL(/\/home$/);
         await page.goto('/catalog');
         await expect(page.getByRole('heading',{name:'Product Catalog'})).toBeVisible();
         await page.getByPlaceholder('Search name, category, brand, SKU, or tag').fill('Running Shoes');
         await page.getByRole('button',{name:'Search'}).click();
         await expect(page.getByRole('heading',{name:'Running Shoes'})).toBeVisible();
         await page.getByRole('link',{name:'View Running Shoes'}).click();
        await expect(page).toHaveURL(/\/running-shoes$/);
        await page.getByLabel("Size").selectOption("UK 10");
        await page.getByRole('radio',{name :'White'}).check();
        await expect(page.getByRole('radio',{name :'White'})).toBeChecked();
        await page.getByLabel('Quantity').fill('2');
        await page.getByRole('radio',{name :'Store pickup'}).check();
        await expect(page.getByRole('radio',{name :'Store pickup'})).toBeChecked();
        await page.getByRole('button',{name: 'Add to Cart'}).click();
        await expect(page).toHaveURL(/\/cart$/);
        await expect(page.getByRole('heading',{name: 'Cart'})).toBeVisible();
        await expect(page.getByTestId('cart-count')).toHaveText('2');
        await page.getByRole('button',{name: 'Proceed to checkout'}).click();
        await expect(page).toHaveURL(/\/checkout$/);
        await page.getByRole('button',{name: 'Place order'}).click();
        await expect(page.getByRole('heading',{name: 'Thank you for your order'})).toBeVisible();
    });
});