stages:
  - test
  - report

playwright-test:
  stage: test
  image: mcr.microsoft.com/playwright:v1.61.0-noble

  parallel: 4

  script:
    - npm ci
    - npx playwright test --config=playwright.config.ts --shard=$CI_NODE_INDEX/$CI_NODE_TOTAL

  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - blob-report/
      - test-results/

playwright-merge-report:
  stage: report
  image: mcr.microsoft.com/playwright:v1.61.0-noble

  needs:
    - job: playwright-test
      artifacts: true

  when: always

  script:
    - npm ci
    - npx playwright merge-reports --reporter html ./blob-report

  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - playwright-report/