name: providerCI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 00. Checkout Code
        uses: actions/checkout@v5

      - name: 0. Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '22'
          cache: 'maven'

      - name: 0. Install Pact CLI
        run: |
          curl -fsSL https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v2.4.5/pact-2.4.5-linux-x86_64.tar.gz | tar xz -C $HOME
          echo "$HOME/pact/bin" >> $GITHUB_PATH

      - name: 1. Run Provider Verification
          working-directory: pact-week4
        continue-on-error: true
        run: |
          mvn -Dtest=ProviderVerification \
              -Dgit.sha=${{ github.sha }} \
              -Dpactbroker.host=127.0.0.1 \
              -Dpactbroker.port=9292 \
              test

      - name: 2. Record provider deployment to production
          working-directory: pact-week4
        run: |
          pact-broker record-deployment \
            --pacticipant provider \
            --version ${{ github.sha }} \
            --environment production \
            --broker-base-url http://127.0.0.1:9292

      - name: 3. Can I deploy
          working-directory: pact-week4
        env:
          CONTRACT_VERSION: ${{ github.sha }}
        run: |
          pact-broker can-i-deploy \
          --pacticipant consumer \
          --version $CONTRACT_VERSION \
          --to-environment production \
          --broker-base-url http://127.0.0.1:9292