name: Pact Consumer

on:
  push:
    branches:
      - lahari_week4_gate4
  pull_request:
    branches:
      - lahari_week4_gate4

jobs:
  consumer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Install Pact CLI
        run: |
          curl -fsSL https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v2.4.5/pact-2.4.5-linux-x86_64.tar.gz | tar xz -C $HOME
          echo "$HOME/pact/bin" >> $GITHUB_PATH

      - name: Start Pact Broker
        run: |
          docker compose -f ProviderConsumerPact/src/test/resources/docker-compose.pact-broker.yml up -d --wait
      - name: Run Consumer Tests
        run: mvn clean test -Dtest=PosOmsConsumerPactTest