name: Consumer CI

on:
  push:
    branches: [ragumaan_04_gate4]
  pull_request:

jobs:
  consumer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "22"
          cache: maven

      - name: Install Pact CLI
        run: |
          curl -fsSL https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v2.4.5/pact-2.4.5-linux-x86_64.tar.gz | tar xz -C $HOME
          echo "$HOME/pact/bin" >> $GITHUB_PATH

      - name: Start Pact Broker
        run: |
          docker compose -f Pacttest/src/test/java/resources/docker/docker-compose.pact-broker.yml down -v
          docker compose -f Pacttest/src/test/java/resources/docker/docker-compose.pact-broker.yml up -d --wait

      - name: Run Consumer Pact Tests
        working-directory: Pacttest
        run: |
          mvn -Dtest=PosOmsConsumerPactTest test

      - name: Publish Contracts
        working-directory: Pacttest
        run: |
          pact-broker publish target/pacts \
            --consumer-app-version=${{ github.sha }} \
            --branch=main \
            --broker-base-url=http://127.0.0.1:9292
