name: Consumer Pipeline

on:
  push:
    branches:
      - main

jobs:
  consumer:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '22'
          cache: maven

      - name: Install Pact CLI
        run: |
          curl -fsSL https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v2.4.5/pact-2.4.5-linux-x86_64.tar.gz | tar xz -C $HOME
          echo "$HOME/pact/bin" >> $GITHUB_PATH

      - name: Start Pact Broker
        run: |
          docker compose -f src/test/resources/docker-compose.pact-broker.yml up -d --wait

      - name: Verify Broker
        run: |
          curl http://127.0.0.1:9292

      - name: Run Consumer Contract Tests
        run: |
          mvn clean test -Dtest=consumer.FoodConsumerPactTest

      - name: Publish Contracts
        run: |
          pact-broker publish target/pacts \
            --consumer-app-version=${{ github.sha }} \
            --branch=main \
            --broker-base-url=http://127.0.0.1:9292

      - name: Can I Deploy Consumer
        run: |
          pact-broker can-i-deploy \
            --pacticipant restaurant-service \
            --version=${{ github.sha }} \
            --to-environment production \
            --broker-base-url=http://127.0.0.1:9292