name: LoadTesting CI

on:
  push:
    branches: [ "Aravind_Final_Capstone" ]
  pull_request:
    branches: [ "Aravind_Final_Capstone" ]

jobs:
  k6_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run k6 UI Performance Test
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            -e K6_BROWSER_ENABLED=true \
            -e ARAVIND_BASE_URL_UI="${{ secrets.ARAVIND_BASE_URL_UI }}" \
            -e ARAVIND_PASSWORD="${{ secrets.ARAVIND_PASSWORD }}" \
            grafana/k6:latest-with-browser run UI/perfomancetesting/load-test.ts