name: providerCI
#
on: [push, pull_request]

jobs:
  provider:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '22'

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}

      - name: Verify Java
        run: java -version

      - name: Verify Maven
        working-directory: pact-week4
        run: mvn -version

      - name: Run Provider Verification
        working-directory: pact-week4
        run: |
          mvn \
            -Dtest=ProviderVerification \
            -Dpactbroker.url=https://rockstar.pactflow.io \
            -Dpactbroker.auth.token=xdlxxgO3kq-b9ps3ih_eKQ \
            -Dpact.verifier.publishResults=true \
            -Dgit.sha=${GITHUB_SHA::7} \
            -Dgit.branch=${GITHUB_REF_NAME} \
            test

      - name: Can I Deploy
        working-directory: pact-week4

        run: |
            mvn au.com.dius.pact.provider:maven:can-i-deploy \
              -Dpact.broker.url=https://rockstar.pactflow.io \
              -Dpact.broker.token=xdlxxgO3kq-b9ps3ih_eKQ \
              -Dpacticipant=consumer \
              -DpacticipantVersion=${GITHUB_SHA::7}