name: provider-ci

on:
  push:
    branches:
      - ManiPrasad-week04-gate4

  workflow_dispatch:

jobs:
  provider:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '22'
          cache: maven

      - name: Install Pact CLI
        run: |
          curl -fsSL https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v2.4.5/pact-2.4.5-linux-x86_64.tar.gz | tar xz -C $HOME
          echo "$HOME/pact/bin" >> $GITHUB_PATH

      - name: Run Provider Verification
        working-directory: Selenide_and_Wiremock
        run: |
          mvn -Dtest=OmsProviderVerification \
              -Dgit.sha=${{ github.sha }} \
              test

      - name: Record Provider Deployment
        working-directory: Selenide_and_Wiremock
        run: |
          pact-broker record-deployment \
            --pacticipant catalog-service \
            --version=${{ github.sha }} \
            --environment production \
            --broker-base-url=https://hgh-46255aa4.pactflow.io \
            --broker-token=7ogUhMOhkXRQiFPRi3JpYg

      - name: Can I Deploy
        working-directory: Selenide_and_Wiremock
        run: |
          pact-broker can-i-deploy \
            --pacticipant storefront \
            --version=${{ github.sha }} \
            --to-environment production \
            --broker-base-url=https://hgh-46255aa4.pactflow.io \
            --broker-token=7ogUhMOhkXRQiFPRi3JpYg