name: Provider Verification

on:
  push:
    branches:
      - bhumika-week04-gate4

jobs:
  provider:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 22

      - name: Run Provider Verification
        working-directory: selenide-wiremock-gate4-bhumika
        run: |
          mvn clean test \
            -Dtest=ProviderVerificationTest \
            -Dpact.broker.url=$PACT_BROKER_BASE_URL \
            -Dpact.broker.token=$PACT_BROKER_TOKEN \
            -Dpact.verifier.publishResults=true \
            -Dpact.provider.version=${GITHUB_SHA::7} \
            -Dgit.branch=${GITHUB_REF_NAME}
