name: consumerCI

on: [push, pull_request]

jobs:
  provider:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '22'

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}
      - name: Verify Java
        run: java -version

      - name: Verify Maven
        working-directory: pact-week4
        run: mvn -version

      - name: Run Provider Verification
        working-directory: pact-week4
        run: |
          mvn \
            -Dtest=ProviderVerification \
            -Dpactbroker.url=https://rockstar.pactflow.io \
            -Dpactbroker.auth.token=xdlxxgO3kq-b9ps3ih_eKQ \
            -Dpact.verifier.publishResults=true \
            -Dgit.sha=${GITHUB_SHA::7} \
            -Dgit.branch=${GITHUB_REF_NAME} \
            test
      - name: Install Pact CLI
        run: |
            curl -fsSL https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v2.4.5/pact-2.4.5-linux-x86_64.tar.gz | tar xz -C $HOME
            echo "$HOME/pact/bin" >> $GITHUB_PATH
      - name: Record Provider Deployment to Production
        run: |
                pact-broker record-deployment \
                  --broker-base-url="https://rockstar.pactflow.io" \
                  --broker-token="xdlxxgO3kq-b9ps3ih_eKQ" \
                  --pacticipant=provider \
                  --version=${GITHUB_SHA::7} \
                  --environment=production
      - name: Can I Deploy
        working-directory: pact-week4
        run: |
            mvn au.com.dius.pact.provider:maven:can-i-deploy \
              -Dpact.broker.url=https://rockstar.pactflow.io \
              -Dpact.broker.token=xdlxxgO3kq-b9ps3ih_eKQ \
              -Dpacticipant=provider \
              -DpacticipantVersion=${GITHUB_SHA::7}
      