name: UI CI

on:
  push:
    branches: [ "Aravind_Final_Capstone" ]
  pull_request:
    branches: [ "Aravind_Final_Capstone" ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: UI

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        env:
          ARAVIND_PASSWORD: ${{ secrets.ARAVIND_PASSWORD }}
          ARAVIND_BASE_URL_UI: ${{ secrets.ARAVIND_BASE_URL_UI }}
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: UI/playwright-report/
          retention-days: 30